<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selanjutnya_1</name>
   <tag></tag>
   <elementGuidId>b4d36759-d7fd-4fab-841b-e25142b63aff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='financial-pensiun-step3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#financial-pensiun-step3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f8f3acc2-04d5-44cd-a1ac-c8d4eb62a7b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>581c40d6-2ac1-4d90-b95b-4d01f24faef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--primary</value>
      <webElementGuid>8cfa60f6-f60e-43e4-a188-44d55670ae54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>financial-pensiun-step3</value>
      <webElementGuid>deb0fa49-2155-461d-a85c-28aa88c3f5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
      <webElementGuid>64de6adf-c7da-411c-98e4-20d991492dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;financial-pensiun-step3&quot;)</value>
      <webElementGuid>357e16c7-f457-45f5-bd8b-e19b3957fe70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='financial-pensiun-step3']</value>
      <webElementGuid>dc97b5d6-e4fe-49a1-835f-75bc57dc3d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='financialCalculatePensiun']/section[3]/div[4]/button</value>
      <webElementGuid>482d2fd2-4ea3-4880-affb-d5e69243020f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rasio Penggantian yang dikehendaki (%)'])[1]/following::button[1]</value>
      <webElementGuid>dba31d47-3bcb-4f2f-b7d7-977a7a0c3101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah pemasukan saat mencapai usia pensiun yang Anda inginkan'])[1]/preceding::button[1]</value>
      <webElementGuid>1afda779-24d3-47c3-a1a0-5ff66796d744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pemasukan pada saat usia pensiun'])[1]/preceding::button[1]</value>
      <webElementGuid>64031b86-7a4c-4bb7-a91f-9215a17d7f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[4]/button</value>
      <webElementGuid>a5a816da-77b1-4478-a311-0fc9a1b0548d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'financial-pensiun-step3' and (text() = 'Selanjutnya' or . = 'Selanjutnya')]</value>
      <webElementGuid>c8b8c2ed-4b94-45fe-9659-842541beca2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
