<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selanjutnya_1_2</name>
   <tag></tag>
   <elementGuidId>951c12c5-9488-4678-add7-308293d4c495</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='financial-pensiun-step4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#financial-pensiun-step4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04b8064a-2e8b-4608-82c6-53a11bf81497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b90a7605-5811-405a-8a3b-622cbe14c60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button--primary</value>
      <webElementGuid>dfa4659d-14bf-4180-97ff-9437fe09194e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>financial-pensiun-step4</value>
      <webElementGuid>f87e32d1-db19-4a41-95fa-c5550ee1e76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selanjutnya</value>
      <webElementGuid>56657b90-033d-4556-a364-c38fa1ab57d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;financial-pensiun-step4&quot;)</value>
      <webElementGuid>be09029f-62f7-4e63-88dd-b30fd418c951</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='financial-pensiun-step4']</value>
      <webElementGuid>8d7ce48a-d7f3-4d58-adbf-edd0461faf82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='financialCalculatePensiun']/section[4]/div[4]/button</value>
      <webElementGuid>0b9f5b26-e1f5-47ef-a34c-013899b62221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lama pensiun yang Anda inginkan (Tahun)'])[1]/following::button[1]</value>
      <webElementGuid>ee4eb891-98df-4a80-996f-e0a0c6b989dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selanjutnya'])[5]/preceding::button[1]</value>
      <webElementGuid>1bcd55e3-d1c5-4af2-b7f7-066d11738075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tingkat inflasi'])[1]/preceding::button[2]</value>
      <webElementGuid>0ef0b9e0-5fe3-4873-8686-00d59cb1d027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div[4]/button</value>
      <webElementGuid>ce1f16dd-7918-435c-ac97-9cb2f8589726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'financial-pensiun-step4' and (text() = 'Selanjutnya' or . = 'Selanjutnya')]</value>
      <webElementGuid>b17d3413-d595-4e4d-9b1a-25f7b131a3c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
