<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lama pensiun yang Anda inginkan (Tahu_dfb7f7</name>
   <tag></tag>
   <elementGuidId>0aa82075-bb1c-4241-a3ee-548a89899658</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pensiunInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pensiunInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ce8ef6f-0018-4b16-91f1-7710cf1f1a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>205df7bd-3b8a-4b0f-a118-ec5116ef655f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formControl</value>
      <webElementGuid>ca67b0bf-49c1-4348-9778-1e293b69b3f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pensiunInput</value>
      <webElementGuid>668058b3-9ab1-4861-8e4b-8f9057aa3301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bd12f4e0-209f-44f0-973e-cdac428d459a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>aeca1d3e-cefb-4221-b9c4-b0d4a76bd437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>42eb1dd5-a554-49b7-aed8-0bcea83afcc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pensiunInput&quot;)</value>
      <webElementGuid>f927bd75-0a38-424b-87ec-bf99e490031e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pensiunInput']</value>
      <webElementGuid>5507ad93-98fe-4d4b-8d2a-09e153027fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='financialCalculatePensiun']/section[4]/div[3]/div[2]/div/div/input</value>
      <webElementGuid>eebbd98d-aaa5-4134-a32d-fad722791620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[4]/div[3]/div[2]/div/div/input</value>
      <webElementGuid>05e7da9f-986f-4f85-832f-6bc65663b9f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'pensiunInput']</value>
      <webElementGuid>ede35aca-bff2-41fc-a1c0-d80d37dbd474</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
