<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Usia Pensiun yang Anda Inginkan (Tahu_a5afd5</name>
   <tag></tag>
   <elementGuidId>adf27b04-12db-4a01-812c-9affefd6d0ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='usiaPensiunInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#usiaPensiunInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38e9fea4-a214-4a89-ba7f-846a9139e15d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>34dcd6d3-ad02-444c-ac93-afe2768baf1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formControl</value>
      <webElementGuid>3b71bb09-a575-4b03-bda9-3cd3a541546b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>73e31dbe-7689-4414-9aad-c8e8ba91e59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>f8e98190-1890-4a8f-9090-5f36c4c37868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usiaPensiunInput</value>
      <webElementGuid>0e07c1ad-e547-4953-b23c-0c204f7424ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>a97a127c-4c6d-4c6e-89a2-1c2e2030ecc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usiaPensiunInput&quot;)</value>
      <webElementGuid>4d0630e5-9a51-41ba-8d6c-70f52ac26e4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='usiaPensiunInput']</value>
      <webElementGuid>15528e1d-703c-4ff0-b378-8455492db4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='financialCalculatePensiun']/section[2]/div[3]/div[2]/div/div/input</value>
      <webElementGuid>7a9e0f07-4e41-474a-a62f-7fd5b6b2e925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>e00a1105-bb6c-4abe-9edb-1d6a578a187e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'usiaPensiunInput']</value>
      <webElementGuid>098aacdf-bdaa-475c-a415-e32e4b15baf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
