<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp_calc_type3</name>
   <tag></tag>
   <elementGuidId>c172ac60-d15c-442a-875a-1dfe950127a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='calc_type3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;calc_type3&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3f7116a-e4d1-482b-9456-3c4f7c6f964f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>960bfdd3-2cab-49be-a93c-f0ecf3f2034d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>calc_type3</value>
      <webElementGuid>2115c14f-b0ee-4d74-bdca-c0ff44a8e216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-for</name>
      <type>Main</type>
      <value>calc_type3</value>
      <webElementGuid>211dad24-25ef-4c9c-abe7-cd4c060d1d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formMoney currency</value>
      <webElementGuid>f683e6d3-7fcc-4aba-b90c-a79e4680f506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Penghasilan Per Bulan</value>
      <webElementGuid>34b71d5b-8add-4ac6-ac1f-8d6ca61994e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;financialCalculatePensiun&quot;)/section[@class=&quot;body-step body-step--1 current&quot;]/div[@class=&quot;content-finder form form--finder&quot;]/div[@class=&quot;content-finder__box&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row row-0&quot;]/div[@class=&quot;col-md-11 col-kurs col-xs-12&quot;]/input[@class=&quot;form-control formMoney currency&quot;]</value>
      <webElementGuid>ae78f8a7-ce24-441d-ad9d-d0a6f5c0ef4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='calc_type3']</value>
      <webElementGuid>918f4966-315a-4143-8d50-28ef978865c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='financialCalculatePensiun']/section/div[3]/div/div/div/div[2]/div/div[2]/input</value>
      <webElementGuid>f0201bca-a2da-4d44-b7e8-ba585e23f70e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>aaa24d84-cbaa-4992-85a8-f316c9df0e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'calc_type3' and @placeholder = 'Penghasilan Per Bulan']</value>
      <webElementGuid>ab8bf35a-3260-4b2b-9820-d75be26ac540</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
