<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rasio Penggantian yang dikehendaki ()_b56598</name>
   <tag></tag>
   <elementGuidId>26bb03f1-08cb-40fb-9448-f146cdc8718a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ratioInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ratioInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f497dc75-4308-4068-be00-165ca81ea12b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>11269c3f-9254-4010-82c7-1f9bbfde298c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formControl</value>
      <webElementGuid>c72e3558-138f-4a30-a1c9-764c8eb1e454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ratioInput</value>
      <webElementGuid>1a239a81-4b1b-4481-9c64-ff5f4ed4444d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>01fe7657-36f5-401d-be7d-28a990f627c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>125</value>
      <webElementGuid>0a123a7d-bdf6-4879-a73f-48443b479f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>503a3c09-fa2e-47de-aca7-3846e2ea16e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ratioInput&quot;)</value>
      <webElementGuid>3904e266-3199-4ceb-b6ff-ec5a5bb868b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ratioInput']</value>
      <webElementGuid>ff5e2e95-6b9f-4034-a2e8-8428ac8631a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='financialCalculatePensiun']/section[3]/div[3]/div/div/div/input</value>
      <webElementGuid>5bdf06c0-fb2e-42e7-9c87-5f836d000a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[3]/div/div/div/input</value>
      <webElementGuid>812836b2-201a-46b4-b6d4-022ba9861c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'ratioInput']</value>
      <webElementGuid>d3dc8af1-8bb4-4f07-827b-c97feb11198c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
