<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_- Silakan pilih di sini -_jcf-select-opener</name>
   <tag></tag>
   <elementGuidId>df059f57-57ac-413d-b803-ec3c77f691ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='protection']/div/div/div/span/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.jcf-select-opener</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d4bfa612-3000-47a0-b232-28c6c138afba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jcf-select-opener</value>
      <webElementGuid>1fd34db5-2f60-4527-aa88-2c1eb3f40eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;protection&quot;)/div[@class=&quot;box-dropdown text-center&quot;]/div[@class=&quot;box-dropdown__item box-dropdown__item--form&quot;]/div[@class=&quot;form-group&quot;]/span[@class=&quot;jcf-select jcf-unselectable jcf-select-formControl jcf-drop-active jcf-focus&quot;]/span[@class=&quot;jcf-select-opener&quot;]</value>
      <webElementGuid>7c67673d-d9ba-4788-9983-720aa6f22090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='protection']/div/div/div/span/span[2]</value>
      <webElementGuid>6b583644-9850-4f84-bb37-7c483bfc7cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>54f9fa6f-5b27-492c-85b0-4cca809b943e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
